language: python

python:
- 2.6
- 2.7
- 3.3

sudo: false

install:
- make -f travis.mk build

script:
- if [ ${TRAVIS_PULL_REQUEST} != "false" ] ; then git fetch origin ${TRAVIS_BRANCH}:${TRAVIS_BRANCH}; fi
- if [ ${TRAVIS_PULL_REQUEST} != "false" ] ; then git diff --check ${TRAVIS_BRANCH} -- ; fi
- make -f travis.mk tests
- make -f travis.mk checks
- travis/status.sh

notifications:
  email:
      on_failure: change
